In [1]:
import numpy as np
from numpy.random import randn

In [4]:
np.set_printoptions (precision=2)

In [9]:
a = np.array([1,2,3,4,5,6])
a

array([1, 2, 3, 4, 5, 6])

In [5]:
np.random.seed (25)
b = randn(6)
b

array([ 0.23,  1.03, -0.84, -0.59, -0.96, -0.22])

In [6]:
np.arange(1 , 12)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [10]:
a + b

array([1.23, 3.03, 2.16, 3.41, 4.04, 5.78])